spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sopt_32?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: sopt_server
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
jwt:
  secret: 12hdaliuwefh2384h1ejwlifahieuurh2o83rhiuhiuhed871hiudha872h3

cloud:
  aws:
    credentials:
      accessKey: AKIAUZDLLGZMA7CAFAOU
      secretKey: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: dong-sopt32-seminar
    stack:
      auto: false

springdoc:
  packages-to-scan: sopt.org.ThirdSeminar
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    tags-sorter: alpah
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
    cache:
      disabled: true